# -*- coding: utf-8 -*-
"""carddekho.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11lnLYt_omDHWeUYiz7Cn05a0zw9yKO5J
"""

import pandas as pd
df=pd.read_csv('/content/cardekho_dataset.csv.zip')
df=df.drop('Unnamed: 0',axis=1)
df

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

df.info()
df.shape

numerical=[col for col in df.columns if df[col].dtype in ['int64', 'float64']]
categorical=[col for col in df.columns if df[col].dtype == 'object']
categorical
numerical

df.describe(include="object")
df.describe()

df.drop_duplicates(inplace=True)
df.shape

#EDA

#1.univariate analysis
plt.figure(figsize=(10,5))
plt.subplot(1,2,1)
sns.distplot(df['selling_price'])
plt.show()

#bivariate analysis
plt.figure(figsize=(10,5))
plt.subplot(1,2,1)
sns.scatterplot(x='km_driven',y='selling_price',data=df)
plt.show()

#multivariate analysis
# Explicitly define numerical list within this cell to ensure correct scope
numerical=[col for col in df.columns if df[col].dtype in ['int64', 'float64']]
df[numerical].corr()

#FEATURE ENGINEERING
model_data=df.copy()

#removing unnecessary columns
model_data.drop(['car_name','brand','model'],axis=1,inplace=True)
model_data

#converting categorical columns to numerical

model_data = pd.get_dummies(model_data, dtype = int)

model_data

#dividing x and y variables
x=model_data.drop('selling_price',axis=1)
y=model_data['selling_price']
y

#train and test spliting
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

#scaling
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

#model building libraries
from sklearn.model_selection import RandomizedSearchCV
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

models=[LinearRegression,SVR,DecisionTreeRegressor,RandomForestRegressor]
value=[]

for model in models:
  regressor=model().fit(x_train,y_train)
  pred=regressor.predict(x_test)
  r2=r2_score(y_true=y_test,y_pred=pred)
  value.append(r2)

print(value)

Evaluation=pd.DataFrame({'model':['LinearRegression','SVR','DecisionTreeRegressor','RandomForestRegressor'],'r2_score':value})
Evaluation

"""Different regression models were trained to predict the selling price of cars using the CarDekho dataset.
The performance of each model was evaluated using the R² Score, which measures how well the model fits the data.

R² = 1 → Perfect prediction

R² = 0 → Poor prediction

R² < 0 → Model failed

Results
Model	R2 Score
Linear Regression	0.67
SVR	-0.08
Decision Tree Regressor	0.82
Random Forest Regressor	0.83
Explanation

Linear Regression performed reasonably well but could not capture non-linear relationships in the dataset.

SVR (Support Vector Regressor) performed poorly and gave a negative R² score, which means the model was not suitable for this dataset.

Decision Tree Regressor performed better because it can handle non-linear relationships between features and target.

Random Forest Regressor gave the best performance with the highest R² score.

Final Model Selection

Random Forest Regressor was selected as the final model because:

It handles non-linear data effectively

It reduces overfitting by combining multiple decision trees

It provided the highest accuracy among all models

Final Model Used: RandomForestRegressor (R² = 0.83)
"""

